# Site settings
title: CloudKernelOS
email: MarkBruns@MarkBruns.com
description: Extreme simplification of container layers for improved reliability
twitter_username: CloudKernelOS
github_username:  CloudKernelOS

# Build settings
markdown: kramdown
